import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeProvider from '@/provider/theme-provider';
import LayoutMain from '@/layouts';
import LanguageProvider from '@/provider/language-provider';
import { Locale } from '@/i18config';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }: { children: React.ReactNode, params: { locale: Locale } }) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <LanguageProvider locale={params.locale}>
          <ThemeProvider>
            <LayoutMain>
              {children}
            </LayoutMain>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
